language: php
php:
  - '5.3'
  - '5.4'
  - hhvm
  - nightly

before_script:
  - if [ "$deps" == "low" ]; then composer update --prefer-source --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer install --prefer-source; fi